declare module 'angular' {  declare var exports: any;  }
declare module 'jquery' {  declare var exports: any;  }
declare module 'jquery-ui' {  declare var exports: any;  }
declare module 'angular-ui-router' {  declare var exports: any;  }
declare module 'angular-ui-grid' {  declare var exports: any;  }
declare module 'angular-ui-sortable' {  declare var exports: any;  }
declare module 'angular-strap/dist/angular-strap' {  declare var exports: any;  }
declare module 'angular-strap/dist/angular-strap.tpl' {  declare var exports: any;  }
declare module 'ui-select' {  declare var exports: any;  }
declare module 'ui-select/dist/select.css' {  declare var exports: any;  }
declare module 'selectize' {  declare var exports: any;  }
declare module 'selectize/dist/css/selectize.default.css' {  declare var exports: any;  }
declare module 'angular-selectize' {  declare var exports: any;  }
declare module 'ng-dialog' {  declare var exports: any;  }
declare module 'ng-dialog/css/ngDialog.min.css' {  declare var exports: any;  }
declare module 'ng-dialog/css/ngDialog-theme-default.min.css' {  declare var exports: any;  }
declare module 'angular-ui-grid/ui-grid.css' {  declare var exports: any;  }
declare module 'jsgrid/dist/jsgrid' {  declare var exports: any;  }
declare module 'jsgrid/dist/jsgrid.css' {  declare var exports: any;  }
declare module 'jsgrid/dist/jsgrid-theme.css' {  declare var exports: any;  }
declare module 'underscore' {  declare var exports: any;  }
declare module 'bootstrap/dist/js/bootstrap' {  declare var exports: any;  }
declare module 'bootstrap/dist/css/bootstrap.css' {  declare var exports: any;  }
declare module 'font-awesome/css/font-awesome.css' {  declare var exports: any;  }